package com.toysmanagement.view;

import com.toysmanagement.model.EmployeeModel;
import javax.swing.table.DefaultTableModel;
import com.toysmanagement.controller.Validation;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.*;



/**
 *
 * @author amritbhattarai
 */
public class EmployeePage extends javax.swing.JFrame {

    /**
     * Creates new form inventory_page
     */
    private final LinkedList<EmployeeModel> employeeList =new LinkedList<>();
    private DefaultTableModel defaultTableModel;
    private final Validation validation;



    public EmployeePage() {
        initComponents(); 
        validation = new Validation();
        
    }
    
    private Boolean createEmployeeModel()
    {
    int ID=Integer.parseInt( fldAddEmpId.getText());
    String Name=fldAddEmpName.getText();
    String Address=fldAddEmpAddress.getText();
    String Contact=fldAddEmpContact.getText();
    String Position=fldAddEmpPosition.getText();
    String Department=fldAddEmpDepartment.getText();

    EmployeeModel newEmployee=new EmployeeModel(ID,Name,Address,Contact,Position, Department);
    if(employeeList.add(newEmployee)){
        loadEmployeeListToTable();
        return true;
    }
    else{
        loadEmployeeListToTable();
        return false;
    }}
    
    
    private void loadEmployeeListToTable(){
     DefaultTableModel model = (DefaultTableModel) tblEmpMain.getModel();
    
    // Clear existing rows
    model.setRowCount(0);

    // Add rows from employeeList
    for (EmployeeModel employee : employeeList) {
        model.addRow(new Object[] {
            employee.getEmpId(),
            employee.getEmpName(),
            employee.getEmpAddress(),
            employee.getEmpContact(),
            employee.getEmpPosition(),
            employee.getEmpDepartment()
        });
    }
}
    private void addEmployeeData(EmployeeModel employee) {
        employeeList.add(employee);
        //Table add
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblEmpMain.getModel();
        defaultTableModel.addRow(new Object[]{
            employee.getEmpId(),
            employee.getEmpName(),
            employee.getEmpAddress(),
            employee.getEmpContact(),
            employee.getEmpPosition(),
            employee.getEmpDepartment()
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmp = new javax.swing.JPanel();
        lblEmpHead = new javax.swing.JLabel();
        btnProducts = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpMain = new javax.swing.JTable();
        lblAddEmpHead = new javax.swing.JLabel();
        lblAddEmpID = new javax.swing.JLabel();
        lblAddEmpPosition = new javax.swing.JLabel();
        lblRemEmpId = new javax.swing.JLabel();
        lblAddEmpName = new javax.swing.JLabel();
        lblAddEmpContact = new javax.swing.JLabel();
        lblAddEmpAddress = new javax.swing.JLabel();
        lblAddEmpDepartment = new javax.swing.JLabel();
        fldAddEmpId = new javax.swing.JTextField();
        fldAddEmpName = new javax.swing.JTextField();
        fldAddEmpAddress = new javax.swing.JTextField();
        fldAddEmpContact = new javax.swing.JTextField();
        fldAddEmpPosition = new javax.swing.JTextField();
        fldAddEmpDepartment = new javax.swing.JTextField();
        btnAddEmp = new javax.swing.JButton();
        lblRemEmpHead = new javax.swing.JLabel();
        fldRemEmpId = new javax.swing.JTextField();
        btnRemEmp = new javax.swing.JButton();
        lblBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpHead.setFont(new java.awt.Font("Helvetica", 1, 72)); // NOI18N
        lblEmpHead.setText("Employees");
        pnlEmp.add(lblEmpHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        btnProducts.setBackground(new java.awt.Color(51, 38, 35));
        btnProducts.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("Products");
        btnProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        pnlEmp.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        btnOrders.setBackground(new java.awt.Color(51, 38, 35));
        btnOrders.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setText("Orders");
        btnOrders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        pnlEmp.add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 50));

        btnSuppliers.setBackground(new java.awt.Color(51, 38, 35));
        btnSuppliers.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnSuppliers.setText("Suppliers");
        btnSuppliers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });
        pnlEmp.add(btnSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 50));

        btnInventory.setBackground(new java.awt.Color(51, 38, 35));
        btnInventory.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventory");
        btnInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        pnlEmp.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 50));

        tblEmpMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Position", "Department", "Contact", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpMain);
        if (tblEmpMain.getColumnModel().getColumnCount() > 0) {
            tblEmpMain.getColumnModel().getColumn(0).setResizable(false);
            tblEmpMain.getColumnModel().getColumn(1).setResizable(false);
            tblEmpMain.getColumnModel().getColumn(2).setResizable(false);
            tblEmpMain.getColumnModel().getColumn(4).setResizable(false);
        }

        pnlEmp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 760, 580));

        lblAddEmpHead.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblAddEmpHead.setText("Add Employee");
        pnlEmp.add(lblAddEmpHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        lblAddEmpID.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddEmpID.setText("Employee ID:");
        pnlEmp.add(lblAddEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, -1, 30));

        lblAddEmpPosition.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddEmpPosition.setText("Position:");
        pnlEmp.add(lblAddEmpPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, -1, 20));

        lblRemEmpId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblRemEmpId.setText("Employee ID:");
        pnlEmp.add(lblRemEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, -1, 30));

        lblAddEmpName.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddEmpName.setText("Name:");
        pnlEmp.add(lblAddEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, -1, -1));

        lblAddEmpContact.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddEmpContact.setText("Contact:");
        pnlEmp.add(lblAddEmpContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 350, -1, -1));

        lblAddEmpAddress.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddEmpAddress.setText("Address:");
        pnlEmp.add(lblAddEmpAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, -1, -1));

        lblAddEmpDepartment.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddEmpDepartment.setText("Department:");
        pnlEmp.add(lblAddEmpDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, -1, -1));

        fldAddEmpId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddEmpId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddEmpIdActionPerformed(evt);
            }
        });
        pnlEmp.add(fldAddEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 60, 30));

        fldAddEmpName.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddEmpName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddEmpNameActionPerformed(evt);
            }
        });
        pnlEmp.add(fldAddEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 250, 140, 30));

        fldAddEmpAddress.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddEmpAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddEmpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddEmpAddressActionPerformed(evt);
            }
        });
        pnlEmp.add(fldAddEmpAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 140, 30));

        fldAddEmpContact.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddEmpContact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddEmpContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddEmpContactActionPerformed(evt);
            }
        });
        pnlEmp.add(fldAddEmpContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 340, 140, 30));

        fldAddEmpPosition.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddEmpPosition.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddEmpPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddEmpPositionActionPerformed(evt);
            }
        });
        pnlEmp.add(fldAddEmpPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 390, 140, 30));

        fldAddEmpDepartment.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddEmpDepartment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddEmpDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddEmpDepartmentActionPerformed(evt);
            }
        });
        pnlEmp.add(fldAddEmpDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 430, 140, 30));

        btnAddEmp.setBackground(new java.awt.Color(51, 38, 35));
        btnAddEmp.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmp.setText("Submit");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        pnlEmp.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 150, 40));

        lblRemEmpHead.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblRemEmpHead.setText("Remove Employee");
        pnlEmp.add(lblRemEmpHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 330, 40));

        fldRemEmpId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldRemEmpId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldRemEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldRemEmpIdActionPerformed(evt);
            }
        });
        pnlEmp.add(fldRemEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 610, 60, 30));

        btnRemEmp.setBackground(new java.awt.Color(51, 38, 35));
        btnRemEmp.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnRemEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnRemEmp.setText("Submit");
        pnlEmp.add(btnRemEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 670, 150, 40));

        lblBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/Background-Others.png"))); // NOI18N
        pnlEmp.add(lblBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1380, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
    this.setVisible(false);
    new ProductsPage().setVisible(true);
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
    this.setVisible(false);
    new OrderPage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
    this.setVisible(false);
    new SuppliersPage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
    this.setVisible(false);
    new InventoryPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void fldRemEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldRemEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldRemEmpIdActionPerformed

    private void fldAddEmpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddEmpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddEmpAddressActionPerformed

    private void fldAddEmpDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddEmpDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddEmpDepartmentActionPerformed

    private void fldAddEmpPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddEmpPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddEmpPositionActionPerformed

    private void fldAddEmpContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddEmpContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddEmpContactActionPerformed

    private void fldAddEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddEmpNameActionPerformed

    private void fldAddEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddEmpIdActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
if (fldAddEmpId.getText().trim().isEmpty() || 
    fldAddEmpName.getText().trim().isEmpty() || 
    fldAddEmpAddress.getText().trim().isEmpty() || 
    fldAddEmpContact.getText().trim().isEmpty() || 
    fldAddEmpPosition.getText().trim().isEmpty() || 
    fldAddEmpDepartment.getText().trim().isEmpty() ||
    Integer.parseInt(fldAddEmpId.getText().trim()) == 0) {
        JOptionPane.showMessageDialog(this,"Please Fill All the Values","Not Sucessful",JOptionPane.ERROR_MESSAGE);
    }
    else{
 if(createEmployeeModel()){
        JOptionPane.showMessageDialog(this,"Student Added","Sucessful",JOptionPane.INFORMATION_MESSAGE);
    }
    else{
         JOptionPane.showMessageDialog(this,"Student not Added","Not Sucessful",JOptionPane.ERROR_MESSAGE);
    }
    }        
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void addEmpDataToTable(EmployeeModel employee)
    {
        employeeList.add(employee);
        defaultTableModel = (DefaultTableModel) tblEmpMain.getModel();
         defaultTableModel.addRow(new Object[]{employee.getEmpId(),
         employee.getEmpName(), employee.getEmpAddress(), employee.getEmpContact(),
         employee.getEmpPosition(), employee.getEmpDepartment()});
    }
     private void registerEmp(EmployeeModel employee) {
        employeeList.add(employee);
        DefaultTableModel model = (DefaultTableModel) tblEmpMain.getModel();
        model.addRow(new Object[]{  
            employee.getEmpId(), employee.getEmpName(), employee.getEmpAddress(),
            employee.getEmpContact(), employee.getEmpPosition(),employee.getEmpDepartment()
        });
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnRemEmp;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JTextField fldAddEmpAddress;
    private javax.swing.JTextField fldAddEmpContact;
    private javax.swing.JTextField fldAddEmpDepartment;
    private javax.swing.JTextField fldAddEmpId;
    private javax.swing.JTextField fldAddEmpName;
    private javax.swing.JTextField fldAddEmpPosition;
    private javax.swing.JTextField fldRemEmpId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddEmpAddress;
    private javax.swing.JLabel lblAddEmpContact;
    private javax.swing.JLabel lblAddEmpDepartment;
    private javax.swing.JLabel lblAddEmpHead;
    private javax.swing.JLabel lblAddEmpID;
    private javax.swing.JLabel lblAddEmpName;
    private javax.swing.JLabel lblAddEmpPosition;
    private javax.swing.JLabel lblBgImg;
    private javax.swing.JLabel lblEmpHead;
    private javax.swing.JLabel lblRemEmpHead;
    private javax.swing.JLabel lblRemEmpId;
    private javax.swing.JPanel pnlEmp;
    private javax.swing.JTable tblEmpMain;
    // End of variables declaration//GEN-END:variables
}
