package com.toysmanagement.view;

import com.toysmanagement.model.InventoryModel;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author amritbhattarai
 */
public class InventoryPage extends javax.swing.JFrame {
    
    
    private final LinkedList<InventoryModel> inventoryList =new LinkedList<>();
    private DefaultTableModel defaultTableModel;
    /**
     * Creates new form inventory_page
     */
    public InventoryPage() {
        
    initComponents();
    
    }
    private Boolean createInventoryModel() {
    int ID = Integer.parseInt(fldAddInventoryId.getText());
    String Name = fldAddInventoryName.getText();
    String Category = fldAddInventoryCategory.getText();
    int Stock = Integer.parseInt(fldAddInventoryStock.getText());
    String Supplier = fldAddInventorySupplier.getText();
    int CPU = Integer.parseInt(fldAddInventoryCPU.getText());
    int TotalValue = Stock * CPU;

    InventoryModel newInventory = new InventoryModel(ID, Name, Category, Stock, Supplier, CPU, TotalValue);
    if (inventoryList.add(newInventory)) {
        loadInventoryListToTable();
        return true;
    } else {
        loadInventoryListToTable();
        return false;
    }
}
    private void loadInventoryListToTable() {
    DefaultTableModel model = (DefaultTableModel) tblInventoryMain.getModel();
    
    // Clear existing rows
    model.setRowCount(0);

    // Add rows from inventoryList
    for (InventoryModel inventory : inventoryList) {
        model.addRow(new Object[] {
            inventory.getInvItemId(),
            inventory.getInvItemName(),
            inventory.getInvItemCategory(),
            inventory.getInvItemStock(),
            inventory.getInvItemSupplier(),
            inventory.getInvItemCpu(),
            inventory.getInvItemTotalValue()
        });
    }
}
    private void addInventoryData(InventoryModel inventory) {
    inventoryList.add(inventory);
    // Table add
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblInventoryMain.getModel();
    defaultTableModel.addRow(new Object[]{
        inventory.getInvItemId(),
        inventory.getInvItemName(),
        inventory.getInvItemCategory(),
        inventory.getInvItemStock(),
        inventory.getInvItemSupplier(),
        inventory.getInvItemCpu(),
        inventory.getInvItemTotalValue()
    });
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInventory = new javax.swing.JPanel();
        lblInventoryHead = new javax.swing.JLabel();
        btnProducts = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventoryMain = new javax.swing.JTable();
        lblAddInventory = new javax.swing.JLabel();
        lblAddInventoryId = new javax.swing.JLabel();
        fldAddInventoryId = new javax.swing.JTextField();
        lblAddInventoryName = new javax.swing.JLabel();
        fldAddInventoryName = new javax.swing.JTextField();
        lblAddInventoryCategory = new javax.swing.JLabel();
        fldAddInventoryCategory = new javax.swing.JTextField();
        lblAddInventoryStock = new javax.swing.JLabel();
        fldAddInventoryStock = new javax.swing.JTextField();
        lblAddInventorySupplier = new javax.swing.JLabel();
        fldAddInventorySupplier = new javax.swing.JTextField();
        lblAddInventoryCPU = new javax.swing.JLabel();
        fldAddInventoryCPU = new javax.swing.JTextField();
        btnAddInventory = new javax.swing.JButton();
        lblRemInventoryHead = new javax.swing.JLabel();
        lblRemInventoryItemId = new javax.swing.JLabel();
        fldRemInventoryId = new javax.swing.JTextField();
        btnRemInventory = new javax.swing.JButton();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInventoryHead.setFont(new java.awt.Font("Helvetica", 1, 72)); // NOI18N
        lblInventoryHead.setText("Inventory");
        pnlInventory.add(lblInventoryHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        btnProducts.setBackground(new java.awt.Color(51, 38, 35));
        btnProducts.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("Products");
        btnProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductsMouseClicked(evt);
            }
        });
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        pnlInventory.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        btnOrders.setBackground(new java.awt.Color(51, 38, 35));
        btnOrders.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setText("Orders");
        btnOrders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        pnlInventory.add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 150, 50));

        btnEmp.setBackground(new java.awt.Color(51, 38, 35));
        btnEmp.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmp.setText("Employee");
        btnEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });
        pnlInventory.add(btnEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 150, 50));

        btnSupplier.setBackground(new java.awt.Color(51, 38, 35));
        btnSupplier.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setText("Suppliers");
        btnSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        pnlInventory.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 50));

        tblInventoryMain.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        tblInventoryMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Name", "Category", "Stock", "Supplier", "Cost Per Unit", "Total Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventoryMain);
        if (tblInventoryMain.getColumnModel().getColumnCount() > 0) {
            tblInventoryMain.getColumnModel().getColumn(0).setResizable(false);
            tblInventoryMain.getColumnModel().getColumn(0).setPreferredWidth(8);
            tblInventoryMain.getColumnModel().getColumn(1).setResizable(false);
            tblInventoryMain.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblInventoryMain.getColumnModel().getColumn(2).setResizable(false);
            tblInventoryMain.getColumnModel().getColumn(3).setResizable(false);
            tblInventoryMain.getColumnModel().getColumn(3).setPreferredWidth(2);
            tblInventoryMain.getColumnModel().getColumn(4).setResizable(false);
            tblInventoryMain.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblInventoryMain.getColumnModel().getColumn(5).setResizable(false);
            tblInventoryMain.getColumnModel().getColumn(5).setPreferredWidth(4);
            tblInventoryMain.getColumnModel().getColumn(6).setResizable(false);
        }

        pnlInventory.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 760, 580));

        lblAddInventory.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblAddInventory.setText("Add Inventory");
        pnlInventory.add(lblAddInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        lblAddInventoryId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddInventoryId.setText("Item ID:");
        pnlInventory.add(lblAddInventoryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, -1, 30));

        fldAddInventoryId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddInventoryId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddInventoryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddInventoryIdActionPerformed(evt);
            }
        });
        pnlInventory.add(fldAddInventoryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 60, 30));

        lblAddInventoryName.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddInventoryName.setText("Name:");
        pnlInventory.add(lblAddInventoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        fldAddInventoryName.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddInventoryName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddInventoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddInventoryNameActionPerformed(evt);
            }
        });
        pnlInventory.add(fldAddInventoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 250, 140, 30));

        lblAddInventoryCategory.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddInventoryCategory.setText("Category");
        pnlInventory.add(lblAddInventoryCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, -1, -1));

        fldAddInventoryCategory.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddInventoryCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddInventoryCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddInventoryCategoryActionPerformed(evt);
            }
        });
        pnlInventory.add(fldAddInventoryCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 140, 30));

        lblAddInventoryStock.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddInventoryStock.setText("Stock");
        pnlInventory.add(lblAddInventoryStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 340, -1, -1));

        fldAddInventoryStock.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddInventoryStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddInventoryStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddInventoryStockActionPerformed(evt);
            }
        });
        pnlInventory.add(fldAddInventoryStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 140, 30));

        lblAddInventorySupplier.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddInventorySupplier.setText("Supplier:");
        pnlInventory.add(lblAddInventorySupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, -1, -1));

        fldAddInventorySupplier.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddInventorySupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddInventorySupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddInventorySupplierActionPerformed(evt);
            }
        });
        pnlInventory.add(fldAddInventorySupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 380, 140, 30));

        lblAddInventoryCPU.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddInventoryCPU.setText("Cost Per Unit");
        pnlInventory.add(lblAddInventoryCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, -1, 20));

        fldAddInventoryCPU.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddInventoryCPU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddInventoryCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddInventoryCPUActionPerformed(evt);
            }
        });
        pnlInventory.add(fldAddInventoryCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 420, 140, 30));

        btnAddInventory.setBackground(new java.awt.Color(51, 38, 35));
        btnAddInventory.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnAddInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnAddInventory.setText("Submit");
        btnAddInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInventoryActionPerformed(evt);
            }
        });
        pnlInventory.add(btnAddInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 490, 150, 40));

        lblRemInventoryHead.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblRemInventoryHead.setText("Remove Inventory");
        pnlInventory.add(lblRemInventoryHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 330, 40));

        lblRemInventoryItemId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblRemInventoryItemId.setText("Item ID:");
        pnlInventory.add(lblRemInventoryItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, -1, 30));

        fldRemInventoryId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldRemInventoryId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldRemInventoryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldRemInventoryIdActionPerformed(evt);
            }
        });
        pnlInventory.add(fldRemInventoryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 610, 60, 30));

        btnRemInventory.setBackground(new java.awt.Color(51, 38, 35));
        btnRemInventory.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnRemInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnRemInventory.setText("Submit");
        btnRemInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemInventoryActionPerformed(evt);
            }
        });
        pnlInventory.add(btnRemInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 680, 150, 40));

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/Background-Others.png"))); // NOI18N
        pnlInventory.add(background_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1380, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
    this.setVisible(false);
    new ProductsPage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
    this.setVisible(false);
    new OrderPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
    this.setVisible(false);
    new EmployeePage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
     this.setVisible(false);
     new SuppliersPage().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void fldAddInventoryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddInventoryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddInventoryIdActionPerformed

    private void fldAddInventoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddInventoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddInventoryNameActionPerformed

    private void fldAddInventoryCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddInventoryCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddInventoryCategoryActionPerformed

    private void fldAddInventoryStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddInventoryStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddInventoryStockActionPerformed

    private void fldAddInventorySupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddInventorySupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddInventorySupplierActionPerformed

    private void fldAddInventoryCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddInventoryCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddInventoryCPUActionPerformed

    private void btnAddInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInventoryActionPerformed
if (fldAddInventoryId.getText().trim().isEmpty() || 
    fldAddInventoryName.getText().trim().isEmpty() || 
    fldAddInventoryCategory.getText().trim().isEmpty() || 
    fldAddInventoryStock.getText().trim().isEmpty() || 
    fldAddInventorySupplier.getText().trim().isEmpty() || 
    fldAddInventoryCPU.getText().trim().isEmpty() ||
    Integer.parseInt(fldAddInventoryId.getText().trim()) == 0 || 
    Integer.parseInt(fldAddInventoryStock.getText().trim()) == 0 || 
    Integer.parseInt(fldAddInventoryCPU.getText().trim()) == 0) {
        JOptionPane.showMessageDialog(this, "Please Fill All the Values", "Not Successful", JOptionPane.ERROR_MESSAGE);
} else {
    if (createInventoryModel()) {
        JOptionPane.showMessageDialog(this, "Inventory Added", "Successful", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Inventory not Added", "Not Successful", JOptionPane.ERROR_MESSAGE);
    }
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddInventoryActionPerformed

    private void fldRemInventoryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldRemInventoryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldRemInventoryIdActionPerformed

    private void btnRemInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemInventoryActionPerformed

    private void btnProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseClicked
        this.setVisible(false);
        new ProductsPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductsMouseClicked

    private void addInventoryDataToTable(InventoryModel inventory) {
    inventoryList.add(inventory);
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblInventoryMain.getModel();
    defaultTableModel.addRow(new Object[]{
        inventory.getInvItemId(),
        inventory.getInvItemName(),
        inventory.getInvItemCategory(),
        inventory.getInvItemStock(),
        inventory.getInvItemSupplier(),
        inventory.getInvItemCpu(),
        inventory.getInvItemTotalValue()
    });
}
private void registerInventory(InventoryModel inventory) {
    inventoryList.add(inventory);
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblInventoryMain.getModel();
    defaultTableModel.addRow(new Object[]{
        inventory.getInvItemId(),
        inventory.getInvItemName(),
        inventory.getInvItemCategory(),
        inventory.getInvItemStock(),
        inventory.getInvItemSupplier(),
        inventory.getInvItemCpu(),
        inventory.getInvItemTotalValue()
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_image;
    private javax.swing.JButton btnAddInventory;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnRemInventory;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JTextField fldAddInventoryCPU;
    private javax.swing.JTextField fldAddInventoryCategory;
    private javax.swing.JTextField fldAddInventoryId;
    private javax.swing.JTextField fldAddInventoryName;
    private javax.swing.JTextField fldAddInventoryStock;
    private javax.swing.JTextField fldAddInventorySupplier;
    private javax.swing.JTextField fldRemInventoryId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddInventory;
    private javax.swing.JLabel lblAddInventoryCPU;
    private javax.swing.JLabel lblAddInventoryCategory;
    private javax.swing.JLabel lblAddInventoryId;
    private javax.swing.JLabel lblAddInventoryName;
    private javax.swing.JLabel lblAddInventoryStock;
    private javax.swing.JLabel lblAddInventorySupplier;
    private javax.swing.JLabel lblInventoryHead;
    private javax.swing.JLabel lblRemInventoryHead;
    private javax.swing.JLabel lblRemInventoryItemId;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JTable tblInventoryMain;
    // End of variables declaration//GEN-END:variables
}
