package com.toysmanagement.view;


import javax.swing.JOptionPane;


/**
 *
 * @author amritbhattarai
 */
public class LoginPageMain extends javax.swing.JFrame {

    /**
     * Creates new form LoginPageMain
     */
    public LoginPageMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblLoginHeadMain = new javax.swing.JLabel();
        lblLoginHeadSub = new javax.swing.JLabel();
        lblLoginEmail = new javax.swing.JLabel();
        fldLoginEmail = new javax.swing.JTextField();
        lblLoginPass = new javax.swing.JLabel();
        fldLoginPass = new javax.swing.JTextField();
        lblLoginIssueInfo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoginHeadMain.setFont(new java.awt.Font("Myanmar MN", 1, 130)); // NOI18N
        lblLoginHeadMain.setForeground(new java.awt.Color(51, 38, 35));
        lblLoginHeadMain.setText("Toys");
        pnlLogin.add(lblLoginHeadMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 320, 190));

        lblLoginHeadSub.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        lblLoginHeadSub.setForeground(new java.awt.Color(51, 38, 35));
        lblLoginHeadSub.setText("Manufacturing System");
        pnlLogin.add(lblLoginHeadSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, 70));

        lblLoginEmail.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        lblLoginEmail.setText("Email:");
        pnlLogin.add(lblLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 60, 30));

        fldLoginEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldLoginEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldLoginEmailActionPerformed(evt);
            }
        });
        pnlLogin.add(fldLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 240, 30));

        lblLoginPass.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblLoginPass.setText("Password:");
        pnlLogin.add(lblLoginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        fldLoginPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldLoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldLoginPassActionPerformed(evt);
            }
        });
        pnlLogin.add(fldLoginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 240, 30));

        lblLoginIssueInfo.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblLoginIssueInfo.setText("Contact the IT Department If Any Issue Occurs");
        pnlLogin.add(lblLoginIssueInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 540, 30));

        btnLogin.setBackground(new java.awt.Color(51, 38, 35));
        btnLogin.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnLogin.setForeground(java.awt.Color.white);
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 90, 30));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/logo main.png"))); // NOI18N
        pnlLogin.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 280, 250));

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/Background-Image.png"))); // NOI18N
        pnlLogin.add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1440, 910));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldLoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldLoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldLoginEmailActionPerformed

    private void fldLoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldLoginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldLoginPassActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       String username = fldLoginEmail.getText();
        String password = fldLoginPass.getText();
        if(username.isEmpty() && password.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please enter username and password.", "Login error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!username.equals("admin")||!password.equals("admin")){
            JOptionPane.showMessageDialog(null, "Username and Password doesn't", "Login error", JOptionPane.ERROR_MESSAGE);
        }
        else {
        this.setVisible(false);
        new WelcomePage().setVisible(true);
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField fldLoginEmail;
    private javax.swing.JTextField fldLoginPass;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblLoginEmail;
    private javax.swing.JLabel lblLoginHeadMain;
    private javax.swing.JLabel lblLoginHeadSub;
    private javax.swing.JLabel lblLoginIssueInfo;
    private javax.swing.JLabel lblLoginPass;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlLogin;
    // End of variables declaration//GEN-END:variables
}
