/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toysmanagement.view;

import com.toysmanagement.model.OrderModel;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author amritbhattarai
 */
public class OrderPage extends javax.swing.JFrame {
    
    private final LinkedList<OrderModel> orderList = new LinkedList<>();
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form order_page
     */
    public OrderPage() {
        initComponents();
    }
    
    private Boolean createOrderModel() {
    int ID = Integer.parseInt(fldAddOrderId.getText());
    String Customer = fldAddOrderCust.getText();
    String Type = fldAddOrderType.getText();
    String Items = fldAddOrderItems.getText();
    String Suppliers = fldAddOrderSupplier.getText();
    int CPU = Integer.parseInt(fldAddOrderCPU.getText());

    OrderModel newOrder = new OrderModel(ID, Customer, Type, Items, Suppliers, CPU);
    if (orderList.add(newOrder)) {
        loadOrderListToTable();
        return true;
    } else {
        loadOrderListToTable();
        return false;
    }
}

private void loadOrderListToTable() {
    DefaultTableModel model = (DefaultTableModel) tblOrderMain.getModel();
    
    // Clear existing rows
    model.setRowCount(0);

    // Add rows from orderList
    for (OrderModel order : orderList) {
        model.addRow(new Object[] {
            order.getOrdId(),
            order.getOrdCust(),
            order.getOrdType(),
            order.getOrdItems(),
            order.getOrdSuppliers(),
            order.getOrdCPU()
        });
    }
}

private void addOrderData(OrderModel order) {
    orderList.add(order);
    // Table add
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblOrderMain.getModel();
    defaultTableModel.addRow(new Object[]{
        order.getOrdId(),
        order.getOrdCust(),
        order.getOrdType(),
        order.getOrdItems(),
        order.getOrdSuppliers(),
        order.getOrdCPU()
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOrder = new javax.swing.JPanel();
        lblOrderHead = new javax.swing.JLabel();
        btnProducts = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderMain = new javax.swing.JTable();
        lblAddOrder = new javax.swing.JLabel();
        lblAddOrderId = new javax.swing.JLabel();
        fldAddOrderId = new javax.swing.JTextField();
        lblAddOrderCust = new javax.swing.JLabel();
        fldAddOrderCust = new javax.swing.JTextField();
        lblAddOrderType = new javax.swing.JLabel();
        fldAddOrderType = new javax.swing.JTextField();
        lblAddOrderItems = new javax.swing.JLabel();
        fldAddOrderItems = new javax.swing.JTextField();
        lblAddOrderSupplier = new javax.swing.JLabel();
        fldAddOrderSupplier = new javax.swing.JTextField();
        lblAddOrderCPU = new javax.swing.JLabel();
        fldAddOrderCPU = new javax.swing.JTextField();
        btnAddOrder = new javax.swing.JButton();
        lblRemOrderHead = new javax.swing.JLabel();
        lblRemOrderId = new javax.swing.JLabel();
        fldRemOrderId = new javax.swing.JTextField();
        btnRemOrder = new javax.swing.JButton();
        lblBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderHead.setFont(new java.awt.Font("Helvetica", 1, 72)); // NOI18N
        lblOrderHead.setText("Orders");
        pnlOrder.add(lblOrderHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        btnProducts.setBackground(new java.awt.Color(51, 38, 35));
        btnProducts.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("Products");
        btnProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        pnlOrder.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        btnInventory.setBackground(new java.awt.Color(51, 38, 35));
        btnInventory.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventory");
        btnInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        pnlOrder.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 150, 50));

        btnEmployee.setBackground(new java.awt.Color(51, 38, 35));
        btnEmployee.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setText("Employee");
        btnEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        pnlOrder.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 150, 50));

        btnSupplier.setBackground(new java.awt.Color(51, 38, 35));
        btnSupplier.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setText("Suppliers");
        btnSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        pnlOrder.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 50));

        tblOrderMain.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        tblOrderMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer/Supplier", "Order Type", "Items", "Quantity", "Cost Per Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderMain);

        pnlOrder.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 760, 580));

        lblAddOrder.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblAddOrder.setText("Add Order");
        pnlOrder.add(lblAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        lblAddOrderId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderId.setText("Order ID:");
        pnlOrder.add(lblAddOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, -1, 30));

        fldAddOrderId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddOrderId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddOrderIdActionPerformed(evt);
            }
        });
        pnlOrder.add(fldAddOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 60, 30));

        lblAddOrderCust.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderCust.setText("Customer/Supplier:");
        pnlOrder.add(lblAddOrderCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, -1, -1));

        fldAddOrderCust.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddOrderCust.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddOrderCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddOrderCustActionPerformed(evt);
            }
        });
        pnlOrder.add(fldAddOrderCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 250, 140, 30));

        lblAddOrderType.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderType.setText("Order Type:");
        pnlOrder.add(lblAddOrderType, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, -1, -1));

        fldAddOrderType.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddOrderType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddOrderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddOrderTypeActionPerformed(evt);
            }
        });
        pnlOrder.add(fldAddOrderType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 140, 30));

        lblAddOrderItems.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderItems.setText("Items:");
        pnlOrder.add(lblAddOrderItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 340, -1, -1));

        fldAddOrderItems.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddOrderItems.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddOrderItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddOrderItemsActionPerformed(evt);
            }
        });
        pnlOrder.add(fldAddOrderItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 140, 30));

        lblAddOrderSupplier.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderSupplier.setText("Supplier:");
        pnlOrder.add(lblAddOrderSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, -1, -1));

        fldAddOrderSupplier.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddOrderSupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddOrderSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddOrderSupplierActionPerformed(evt);
            }
        });
        pnlOrder.add(fldAddOrderSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 370, 140, 30));

        lblAddOrderCPU.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderCPU.setText("Cost Per Unit");
        pnlOrder.add(lblAddOrderCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, -1, 20));

        fldAddOrderCPU.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddOrderCPU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddOrderCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddOrderCPUActionPerformed(evt);
            }
        });
        pnlOrder.add(fldAddOrderCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 410, 140, 30));

        btnAddOrder.setBackground(new java.awt.Color(51, 38, 35));
        btnAddOrder.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrder.setText("Submit");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });
        pnlOrder.add(btnAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 490, 150, 40));

        lblRemOrderHead.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblRemOrderHead.setText("Remove Order");
        pnlOrder.add(lblRemOrderHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 330, 40));

        lblRemOrderId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblRemOrderId.setText("Order ID:");
        pnlOrder.add(lblRemOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, -1, 30));

        fldRemOrderId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldRemOrderId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldRemOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldRemOrderIdActionPerformed(evt);
            }
        });
        pnlOrder.add(fldRemOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 610, 60, 30));

        btnRemOrder.setBackground(new java.awt.Color(51, 38, 35));
        btnRemOrder.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnRemOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnRemOrder.setText("Submit");
        btnRemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemOrderActionPerformed(evt);
            }
        });
        pnlOrder.add(btnRemOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 670, 150, 40));

        lblBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/Background-Others.png"))); // NOI18N
        pnlOrder.add(lblBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1380, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
    this.setVisible(false);
    new ProductsPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
    this.setVisible(false);
    new InventoryPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
    this.setVisible(false);
    new EmployeePage().setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
    this.setVisible(false);
    new SuppliersPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void fldAddOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddOrderIdActionPerformed

    private void fldAddOrderCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddOrderCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddOrderCustActionPerformed

    private void fldAddOrderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddOrderTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddOrderTypeActionPerformed

    private void fldAddOrderItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddOrderItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddOrderItemsActionPerformed

    private void fldAddOrderSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddOrderSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddOrderSupplierActionPerformed

    private void fldAddOrderCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddOrderCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddOrderCPUActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
    if (fldAddOrderId.getText().trim().isEmpty() || 
    fldAddOrderCust.getText().trim().isEmpty() || 
    fldAddOrderType.getText().trim().isEmpty() || 
    fldAddOrderItems.getText().trim().isEmpty() || 
    fldAddOrderSupplier.getText().trim().isEmpty() || 
    fldAddOrderCPU.getText().trim().isEmpty() ||
    Integer.parseInt(fldAddOrderId.getText().trim()) == 0 || 
    Integer.parseInt(fldAddOrderCPU.getText().trim()) == 0) {
        
    JOptionPane.showMessageDialog(this, "Please Fill All the Values", "Not Successful", JOptionPane.ERROR_MESSAGE);
} else {
    if (createOrderModel()) {
        JOptionPane.showMessageDialog(this, "Order Added", "Successful", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Order not Added", "Not Successful", JOptionPane.ERROR_MESSAGE);
    }
}

// TODO add your handling code here:
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void fldRemOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldRemOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldRemOrderIdActionPerformed

    private void btnRemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemOrderActionPerformed

    private void addOrderDataToTable(OrderModel order) {
    orderList.add(order);
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblOrderMain.getModel();
    defaultTableModel.addRow(new Object[]{
        order.getOrdId(),
        order.getOrdCust(),
        order.getOrdType(),
        order.getOrdItems(),
        order.getOrdSuppliers(),
        order.getOrdCPU()
    });
}

private void registerOrder(OrderModel order) {
    orderList.add(order);
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblOrderMain.getModel();
    defaultTableModel.addRow(new Object[]{
        order.getOrdId(),
        order.getOrdCust(),
        order.getOrdType(),
        order.getOrdItems(),
        order.getOrdSuppliers(),
        order.getOrdCPU()
    });
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnRemOrder;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JTextField fldAddOrderCPU;
    private javax.swing.JTextField fldAddOrderCust;
    private javax.swing.JTextField fldAddOrderId;
    private javax.swing.JTextField fldAddOrderItems;
    private javax.swing.JTextField fldAddOrderSupplier;
    private javax.swing.JTextField fldAddOrderType;
    private javax.swing.JTextField fldRemOrderId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrder;
    private javax.swing.JLabel lblAddOrderCPU;
    private javax.swing.JLabel lblAddOrderCust;
    private javax.swing.JLabel lblAddOrderId;
    private javax.swing.JLabel lblAddOrderItems;
    private javax.swing.JLabel lblAddOrderSupplier;
    private javax.swing.JLabel lblAddOrderType;
    private javax.swing.JLabel lblBgImg;
    private javax.swing.JLabel lblOrderHead;
    private javax.swing.JLabel lblRemOrderHead;
    private javax.swing.JLabel lblRemOrderId;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JTable tblOrderMain;
    // End of variables declaration//GEN-END:variables
}
