/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toysmanagement.view;

import com.toysmanagement.model.ProductModel;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author amritbhattarai
 */
public class ProductsPage extends javax.swing.JFrame {

private final LinkedList<ProductModel> productList = new LinkedList<>();
private DefaultTableModel defaultTableModel;

/**
 * Creates new form product_page
 */
public ProductsPage() {
    initComponents();
}

private Boolean createProductModel() {
    int ID = Integer.parseInt(fldAddProductId.getText());
    String Name = fldAddProductName.getText();
    String Category = fldAddProductCategory.getText();
    String Supplier = fldAddProductSupplier.getText();
    int Quantity = Integer.parseInt(fldAddProductQuantity.getText());
    int CPU = Integer.parseInt(fldAddProductCPU.getText());
    int TotalValue = Quantity * CPU;

    ProductModel newProduct = new ProductModel(ID, Name, Category, Supplier, Quantity, CPU, TotalValue);
    if (productList.add(newProduct)) {
        loadProductListToTable();
        return true;
    } else {
        loadProductListToTable();
        return false;
    }
}

private void loadProductListToTable() {
    DefaultTableModel model = (DefaultTableModel) tblProductMain.getModel();
    
    // Clear existing rows
    model.setRowCount(0);

    // Add rows from productList
    for (ProductModel product : productList) {
        model.addRow(new Object[] {
            product.getProdId(),
            product.getProdName(),
            product.getProdCategory(),
            product.getProdSupplier(),
            product.getProdQuantity(),
            product.getProdCpu(),
            product.getProdTotalValue()
        });
    }
}

private void addProductData(ProductModel product) {
    productList.add(product);
    // Table add
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblProductMain.getModel();
    defaultTableModel.addRow(new Object[]{
        product.getProdId(),
        product.getProdName(),
        product.getProdCategory(),
        product.getProdSupplier(),
        product.getProdQuantity(),
        product.getProdCpu(),
        product.getProdTotalValue()
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProducts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductMain = new javax.swing.JTable();
        lblProductsHead = new javax.swing.JLabel();
        btnInventory = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        lblAddProducts = new javax.swing.JLabel();
        lblAddProductId = new javax.swing.JLabel();
        fldAddProductId = new javax.swing.JTextField();
        lblAddProductName = new javax.swing.JLabel();
        fldAddProductName = new javax.swing.JTextField();
        lblAddProductCategory = new javax.swing.JLabel();
        fldAddProductCategory = new javax.swing.JTextField();
        lblAddProductSupplier = new javax.swing.JLabel();
        fldAddProductSupplier = new javax.swing.JTextField();
        lblAddProductQuantity = new javax.swing.JLabel();
        fldAddProductQuantity = new javax.swing.JTextField();
        lblAddProductCPU = new javax.swing.JLabel();
        fldAddProductCPU = new javax.swing.JTextField();
        lblAddOrderTotalValue = new javax.swing.JLabel();
        fldAddProductTotalValue = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        lblRemProductHead = new javax.swing.JLabel();
        lblRemProductId = new javax.swing.JLabel();
        fldRemProductId = new javax.swing.JTextField();
        btnRemOrder = new javax.swing.JButton();
        lblBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 228, 204));

        pnlProducts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductMain.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        tblProductMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Category", "Supplier", "Quantity", "Cost Per Unit", "Total Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductMain);
        if (tblProductMain.getColumnModel().getColumnCount() > 0) {
            tblProductMain.getColumnModel().getColumn(0).setResizable(false);
            tblProductMain.getColumnModel().getColumn(1).setResizable(false);
            tblProductMain.getColumnModel().getColumn(2).setResizable(false);
            tblProductMain.getColumnModel().getColumn(3).setResizable(false);
            tblProductMain.getColumnModel().getColumn(4).setResizable(false);
            tblProductMain.getColumnModel().getColumn(6).setResizable(false);
        }

        pnlProducts.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 760, 580));

        lblProductsHead.setFont(new java.awt.Font("Helvetica", 1, 72)); // NOI18N
        lblProductsHead.setText("Products");
        pnlProducts.add(lblProductsHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        btnInventory.setBackground(new java.awt.Color(51, 38, 35));
        btnInventory.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventory");
        btnInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        pnlProducts.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        btnOrders.setBackground(new java.awt.Color(51, 38, 35));
        btnOrders.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setText("Orders");
        btnOrders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        pnlProducts.add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 50));

        btnEmployee.setBackground(new java.awt.Color(51, 38, 35));
        btnEmployee.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setText("Employee");
        btnEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        pnlProducts.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 50));

        btnSupplier.setBackground(new java.awt.Color(51, 38, 35));
        btnSupplier.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setText("Suppliers");
        btnSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        pnlProducts.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 50));

        lblAddProducts.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblAddProducts.setText("Add Products");
        pnlProducts.add(lblAddProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        lblAddProductId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddProductId.setText("Product Id");
        pnlProducts.add(lblAddProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, -1, 30));

        fldAddProductId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductIdActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 210, 60, 30));

        lblAddProductName.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddProductName.setText("Name");
        pnlProducts.add(lblAddProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, -1, -1));

        fldAddProductName.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductNameActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 250, 140, 30));

        lblAddProductCategory.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddProductCategory.setText("Category");
        pnlProducts.add(lblAddProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, -1, -1));

        fldAddProductCategory.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductCategoryActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 140, 30));

        lblAddProductSupplier.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddProductSupplier.setText("Supplier");
        pnlProducts.add(lblAddProductSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, -1, -1));

        fldAddProductSupplier.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductSupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductSupplierActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 140, 30));

        lblAddProductQuantity.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddProductQuantity.setText("Quantity");
        pnlProducts.add(lblAddProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, -1, -1));

        fldAddProductQuantity.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductQuantity.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductQuantityActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 370, 140, 30));

        lblAddProductCPU.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddProductCPU.setText("Cost Per Unit");
        pnlProducts.add(lblAddProductCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, -1, 20));

        fldAddProductCPU.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductCPU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductCPUActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 410, 140, 30));

        lblAddOrderTotalValue.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblAddOrderTotalValue.setText("Total Value");
        pnlProducts.add(lblAddOrderTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, 20));

        fldAddProductTotalValue.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldAddProductTotalValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldAddProductTotalValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAddProductTotalValueActionPerformed(evt);
            }
        });
        pnlProducts.add(fldAddProductTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, 140, 30));

        btnAddProduct.setBackground(new java.awt.Color(51, 38, 35));
        btnAddProduct.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Submit");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        pnlProducts.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 490, 150, 40));

        lblRemProductHead.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblRemProductHead.setText("Remove Product");
        pnlProducts.add(lblRemProductHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 330, 40));

        lblRemProductId.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        lblRemProductId.setText("Product Id:");
        pnlProducts.add(lblRemProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, -1, 30));

        fldRemProductId.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        fldRemProductId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldRemProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldRemProductIdActionPerformed(evt);
            }
        });
        pnlProducts.add(fldRemProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 610, 60, 30));

        btnRemOrder.setBackground(new java.awt.Color(51, 38, 35));
        btnRemOrder.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        btnRemOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnRemOrder.setText("Submit");
        btnRemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemOrderActionPerformed(evt);
            }
        });
        pnlProducts.add(btnRemOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 670, 150, 40));

        lblBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/Background-Others.png"))); // NOI18N
        pnlProducts.add(lblBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1380, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
    this.setVisible(false);
    new InventoryPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
    this.setVisible(false);
    new OrderPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
    this.setVisible(false);
    new EmployeePage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
    this.setVisible(false);
    new SuppliersPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void fldAddProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductIdActionPerformed

    private void fldAddProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductNameActionPerformed

    private void fldAddProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductCategoryActionPerformed

    private void fldAddProductSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductSupplierActionPerformed

    private void fldAddProductQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductQuantityActionPerformed

    private void fldAddProductCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductCPUActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        if (fldAddProductId.getText().trim().isEmpty() || 
    fldAddProductName.getText().trim().isEmpty() || 
    fldAddProductCategory.getText().trim().isEmpty() || 
    fldAddProductQuantity.getText().trim().isEmpty() || 
    fldAddProductSupplier.getText().trim().isEmpty() || 
    fldAddProductCPU.getText().trim().isEmpty() ||
    Integer.parseInt(fldAddProductId.getText().trim()) == 0 || 
    Integer.parseInt(fldAddProductQuantity.getText().trim()) == 0 || 
    Integer.parseInt(fldAddProductCPU.getText().trim()) == 0) {
        
    JOptionPane.showMessageDialog(this, "Please Fill All the Values", "Not Successful", JOptionPane.ERROR_MESSAGE);
} else {
    if (createProductModel()) {
        JOptionPane.showMessageDialog(this, "Product Added", "Successful", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Product not Added", "Not Successful", JOptionPane.ERROR_MESSAGE);
    }
}


        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void fldRemProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldRemProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldRemProductIdActionPerformed

    private void btnRemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemOrderActionPerformed

    private void fldAddProductTotalValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAddProductTotalValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAddProductTotalValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnRemOrder;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JTextField fldAddProductCPU;
    private javax.swing.JTextField fldAddProductCategory;
    private javax.swing.JTextField fldAddProductId;
    private javax.swing.JTextField fldAddProductName;
    private javax.swing.JTextField fldAddProductQuantity;
    private javax.swing.JTextField fldAddProductSupplier;
    private javax.swing.JTextField fldAddProductTotalValue;
    private javax.swing.JTextField fldRemProductId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrderTotalValue;
    private javax.swing.JLabel lblAddProductCPU;
    private javax.swing.JLabel lblAddProductCategory;
    private javax.swing.JLabel lblAddProductId;
    private javax.swing.JLabel lblAddProductName;
    private javax.swing.JLabel lblAddProductQuantity;
    private javax.swing.JLabel lblAddProductSupplier;
    private javax.swing.JLabel lblAddProducts;
    private javax.swing.JLabel lblBgImg;
    private javax.swing.JLabel lblProductsHead;
    private javax.swing.JLabel lblRemProductHead;
    private javax.swing.JLabel lblRemProductId;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JTable tblProductMain;
    // End of variables declaration//GEN-END:variables
}
