/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toysmanagement.view;

/**
 *
 * @LMUID 23048624
 * @author amritbhattarai
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form welcome_page
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        products_panel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblWelcomeTxt = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtWelcomeMsg = new javax.swing.JTextArea();
        lblBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        products_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        products_panel.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 280, 250));

        lblWelcomeTxt.setFont(new java.awt.Font("Helvetica", 1, 72)); // NOI18N
        lblWelcomeTxt.setText("Welcome");
        products_panel.add(lblWelcomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        btnNext.setBackground(new java.awt.Color(51, 38, 35));
        btnNext.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        products_panel.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 150, 50));

        jScrollPane1.setBorder(null);

        txtWelcomeMsg.setEditable(false);
        txtWelcomeMsg.setBackground(new java.awt.Color(255, 228, 204));
        txtWelcomeMsg.setColumns(20);
        txtWelcomeMsg.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        txtWelcomeMsg.setRows(5);
        txtWelcomeMsg.setText("Welcome to the Toys Manufacturing System Of Jurasis Toys. \nThis program can help the admins of the company to help add, view\n, edit, delete the records of employees, inventory, products and \nsuppliers. \n\nWe hope that the people that are using this software can have an easier \nalternative to traditional book keeping methods. ");
        txtWelcomeMsg.setBorder(null);
        jScrollPane1.setViewportView(txtWelcomeMsg);

        products_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 610, 220));

        lblBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toysmanagement/resources/Background-Image.png"))); // NOI18N
        products_panel.add(lblBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1440, 910));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(products_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(products_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.setVisible(false);
        new ProductsPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBgImg;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblWelcomeTxt;
    private javax.swing.JPanel products_panel;
    private javax.swing.JTextArea txtWelcomeMsg;
    // End of variables declaration//GEN-END:variables
}
